pipeline:
  name: expression-test
  identifier: expressiontest
  projectIdentifier: testing
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: custom-stage
        identifier: customstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
        when:
          condition: <+pipeline.variables.safetodanceEnabled>=="true"
