pipeline:
  name: inline-pipeline
  identifier: inlinepipeline
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: custom-stage
        identifier: customstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
    - stage:
        name: testing
        identifier: testing
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginxservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: nginximage
                          type: DockerRegistry
                          spec:
                            tag: <+input>
                  variables:
                    - name: test_variable
                      type: String
                      value: <+input>
          environment:
            environmentRef: helmenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helm
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
